[package]
name = "hydroflow_plus"
publish = true
version = "0.7.0"
edition = "2021"
license = "Apache-2.0"
documentation = "https://docs.rs/hydroflow_plus/"
description = "Functional programming API for hydroflow"

[lib]
path = "src/lib.rs"

[features]
default = []
diagnostics = [ "hydroflow_lang/diagnostics" ]
cli_integration = [ "hydroflow/cli_integration" ]

[dependencies]
quote = "1.0.0"
syn = { version = "2.0.0", features = [ "parsing", "extra-traits", "visit-mut" ] }
proc-macro2 = "1.0.57"
proc-macro-crate = "1.1.0"
hydroflow = { path = "../hydroflow", version = "^0.7.0", default-features = false }
hydroflow_lang = { path = "../hydroflow_lang", version = "^0.7.0" }
serde = { version = "1", features = [ "derive" ] }
bincode = "1.3"
stageleft = { path = "../stageleft", version = "^0.3.0" }
dyn-clone = "1.0.17"

# added to workaround `cargo smart-release` https://github.com/Byron/cargo-smart-release/issues/16
stageleft_tool = { path = "../stageleft_tool", version = "^0.2.0", optional = true }

[build-dependencies]
stageleft_tool = { path = "../stageleft_tool", version = "^0.2.0" }

[dev-dependencies]
insta = "1.7.1"
