[package]
name = "lattices"
publish = true
version = "0.5.5"
edition = "2021"
license = "Apache-2.0"
documentation = "https://docs.rs/lattices/"
description = "Lattice data types for simplifying distributed state by providing associativity, commutativity, and idempotence."

[features]
default = []
serde = ["dep:serde"]

[dependencies]
cc-traits = "2.0.0"
sealed = "0.5"
serde = { version = "1.0.160", features = ["derive"], optional = true }
trybuild = "1.0.80"
lattices_macro = { path = "../lattices_macro", version = "^0.5.5" }
