[package]
name = "hydroflow_plus_cli_integration"
publish = true
version = "0.7.0"
edition = "2021"
license = "Apache-2.0"
documentation = "https://docs.rs/hydroflow_plus_cli_integration/"
description = "Library for working with hydro_deploy and hydroflow_plus"

[features]
default = []
deploy = [ "hydro_deploy", "async-channel" ]

[dependencies]
stageleft = { path = "../../stageleft", version = "^0.3.0" }
hydroflow_plus = { path = "../../hydroflow_plus", version = "^0.7.0", features = [ "cli_integration" ] }
syn = { version = "2.0.0", features = [ "parsing", "extra-traits" ] }
tokio = { version = "1.16", features = [ "full" ] }
serde = { version = "1", features = [ "derive" ] }

hydro_deploy = { path = "../core", version = "^0.7.0", optional = true }
async-channel = { version = "1.8.0", optional = true }

# added to workaround `cargo smart-release` https://github.com/Byron/cargo-smart-release/issues/16
stageleft_tool = { path = "../../stageleft_tool", version = "^0.2.0", optional = true }

[build-dependencies]
stageleft_tool = { path = "../../stageleft_tool", version = "^0.2.0" }
