[package]
name = "hydro_cli"
publish = true
version = "0.7.0"
edition = "2021"
license = "Apache-2.0"
documentation = "https://docs.rs/hydro_cli/"
description = "Hydro Deploy Command Line Interface"

[lib]
name = "hydro_cli"
# "cdylib" is necessary to produce a shared library for Python to import from.
crate-type = ["cdylib"]

[dependencies]
hydro_deploy = { path = "../core", version = "^0.7.0" }
tokio = { version = "1.16", features = [ "full" ] }
once_cell = "1.17"
anyhow = { version = "1.0.69", features = [ "backtrace" ] }
clap = { version = "4.1.8", features = ["derive"] }
pyo3 = { version = "0.20", features = ["abi3-py37"] }
pyo3-asyncio = { version = "0.20", features = ["attributes", "tokio-runtime"] }
pythonize = "0.20"
futures = "0.3.26"
async-channel = "1.8.0"
bytes = "1.1.0"
hydroflow_cli_integration = { path = "../hydroflow_cli_integration", version = "^0.5.2" }

# request vendored openssl
async-ssh2-lite = { version = "0.4.2", features = [ "vendored-openssl" ] }
