[package]
name = "pusherator"
publish = true
version = "0.0.6"
edition = "2021"
license = "Apache-2.0"
documentation = "https://docs.rs/pusherator/"
description = "Push-based version of Rust iterators"

[features]
default = [ "demux" ]
demux = [ "dep:variadics" ]

[dependencies]
either = "1.8.0"
variadics = { optional = true, path = "../variadics", version = "^0.0.4" }
